Name: Bharat Modhwadiya
bm3339@drexel.edu
(267)312-3546

# Introduction to deep learning with PyTorch

What is deep learning?
Deep learning is everywhere:
• Language translation
• Self-driving cars
• Medical diagnostics
• Chatbots
• Used on multiple data types: images, text and audio

**Traditional machine learning: relies on hand-crafted feature engineering
### Where Deep Learning enables feature learning from raw data



Deep learning is a subset of machine learning
• Inspired by connections in the human brain
• Models require large amount of data

PyTorch: a deep learning framework
PyTorch is one of the most popular deep learning frameworks 
• the framework used in many published deep learning papers
• intuitive and user-friendly
• has much in common with NumPy

In [1]:
#Imporiting PyTorch and related package

import torch
# Image data with torchvision
# Audio data with torchaudio
# Text data with torchtext

Fundamental data structure in PyTorch is called 'Tensors'
Tensors : the building bloack of Networks in PyTorch

#### A tensor is a mathematical object representing a multi-dimensional array of numerical values.

we can load torch from list and NumPy array 

lst = [[1,2,3],[4,5,6]]
tensor = torch.tensor(lst)

or

np_array = np.array(array)
np_tensor = torch.from_numpy(np_array)

### Tensor Attributes 

• Tensor Shape : to check the size of created tensor tensor.shape
• Tensor data type - tensor.dtype
• Tensor Device - tensor.device

Deep Learning often requires a GPU, which compared to a CPU can offer:
• Parralel Computing capabilities
• Faster training times
• Better Performance

Most NumPy array Operations can be performed on PyTorch tensors

In [2]:

list_a = [1, 2, 3, 4]

# Create a tensor from list_a
tensor_a = torch.tensor(list_a)

print(tensor_a)

tensor([1, 2, 3, 4])


In [3]:
# Display the tensor device
print(tensor_a.device)

# Display the tensor data type
print(tensor_a.dtype)

cpu
torch.int64


Creating tensors from NumPy arrays
Tensors are the fundamental data structure of PyTorch. You can create complex deep learning algorithms by learning how to manipulate them.

The torch package has been imported, and two NumPy arrays have been created, named array_a and array_b. Both arrays have the same dimensions.

In [ ]:
# Create two tensors from the arrays
tensor_a = torch.tensor(array_a)
tensor_b = torch.tensor(array_b)

# Subtract tensor_b from tensor_a 
tensor_c = tensor_a - tensor_b

# Multiply each element of tensor_a with each element of tensor_b
tensor_d = tensor_a*tensor_b

# Add tensor_c with tensor_d
tensor_e = tensor_c+tensor_d
print(tensor_e)

## Creating our first neural network

In [4]:
import torch.nn as nn

## Create input_tensor with three features
input_tensor = torch.tensor([[0.3471, 0.4547,-0.235611]])

#define our first Linear layer 
linear_layer = nn.Linear(in_features = 3, out_features=2)

In [5]:
# Pass input through linear layer

output = linear_layer(input_tensor)

print(output)

tensor([[-0.1320, -0.5357]], grad_fn=<AddmmBackward0>)


In [6]:
## Each Linear layer has weight and bias property

In [8]:
print(linear_layer.weight)
print(linear_layer.bias)

Parameter containing:
tensor([[ 0.1236, -0.4734,  0.4159],
        [ 0.1976, -0.4156,  0.3515]], requires_grad=True)
Parameter containing:
tensor([ 0.1384, -0.3325], requires_grad=True)


Getting to know the linear layer operation
output = linear_layer(input_tensor)
For input X, weights W0 and bias b0, the linear layer performs
yo = W0*X + b0
In PyTorch: output = W0 @ input + b0
#### Weights and biases are initialized randomly
• They are not useful until they are tuned

In [14]:
## USE of nn.Sequential

input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

# Implement a small neural network with exactly two linear layers
model = nn.Sequential(nn.Linear(8,1),
                      nn.Linear(1,1)
                     )

output = model(input_tensor)
print(output)

tensor([[0.0948]], grad_fn=<AddmmBackward0>)


#### In practice, you'll find that modern neural networks can contain hundreds of layers and millions of parameters. Recall that the model output is not meaningful until the model is trained, i.e. until the weights and biases of each layer can meaningfully be used to produce output.

### Discovering activation functions

Till time we have seen linear operation and linear output. But we can create non-linear output as well using activation function. Activation functions adds non-linearity to the network.
#### pre-activation output and output after activation.

### SIGMOID FUNCTION

### Used for Binary classification task. 

Let's say we have 3 input as limbs(4), layseggs?(0), have hair? (1).. Now we want to that is that animal is mamal or not. 
To predict whether animal is 1 (mammal) or O (not mammal),
• we got the pre-activation (6),
now pass it to the sigmoid, and obtain a value between 0 and 1.
Using the common threshold of 0.5:
• If output is > 0.5, class label = 1 (mammal)
• If output is <= 0.5, class label = 0 (not mammal)


In [17]:
input_tensor = torch.Tensor([[6.0]])
Sigmoid = nn.Sigmoid()
output = Sigmoid(input_tensor)
output

tensor([[0.9975]])

Sigmoid is used as last step when using nn.Sequential to check for binary classification task.

#### What can be used for Multi Class Classification Problem ??
## INTRODUCINT 'SOFTMAX'

say N=3 classes:
• bird (0), mammal (1), reptile (2)
• output has three elements, so softmax has three elements
• outputs a probability distribution:
• each element is a probability (it's bounded between 0 and 1)
• the sum of the output vector is equal to 1

### probabilities = nn.Softmax(dim=-1)
### output_tensor = probabilities(input_tensor)
### dim = -1 indicates softmax is applied to the input tensor's last dimension
### nn. Sigmoid() can be used as last step in nn. Sequential()

In [18]:
input_tensor = torch.tensor([[1.0, -6.0, 2.5, -0.3, 1.2, 0.8]])

# Create a softmax function and apply it on input_tensor
softmax = nn.Softmax(dim=-1)
probabilities = softmax(input_tensor)
print(probabilities)

tensor([[1.2828e-01, 1.1698e-04, 5.7492e-01, 3.4961e-02, 1.5669e-01, 1.0503e-01]])


### Running a forward pass

In [22]:
import torch
import torch.nn as nn

input_tensor = torch.Tensor([[3, 4, 6, 2, 3, 6, 8, 9]])

# Implement a small neural network for binary classification
model = nn.Sequential(
  nn.Linear(8,1),
  nn.Sigmoid()
)

output = model(input_tensor)
print(output)

tensor([[0.8681]], grad_fn=<SigmoidBackward0>)


The sigmoid output cannot return any float value: the output returned by your binary classifier is bounded between zero and one.

In [25]:
#Practice 
input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Update network below to perform a multi-class classification with four labels
model = nn.Sequential(
  nn.Linear(11, 20),
  nn.Linear(20, 12),
  nn.Linear(12, 6),
  nn.Linear(6, 4), 
  nn.Softmax(dim=-1)
)

output = model(input_tensor)
print(output)

tensor([[0.1510, 0.3198, 0.0847, 0.4446]], grad_fn=<SoftmaxBackward0>)


Why do we need a loss function ?
How do we know that predection values are acturate or it has errors. 

Loss function gives feedback to model during training. Our goal is to minimise the loss.

Loss = F(y,ý) ý is Y hat

y is single integer (class label) 0 or 1.

ý is Tensor (output of Softmax function)
Let's N=3. ý = [0.57492, 0.034961, 0.156691]

HOW do we compare an integer with a tensor ??

## ONE-HOT Encoding is used now

import torch.nn.functional as F

F.one_hot(torch.tensor(0),num_classes=3)

## CROSS ENTROPY LOSS in PyTorch
it is the most used loss function in classification problem in pytorch.


In [28]:
import torch
import torch.nn as nn
import torch.nn.functional as F

y = [2]
scores = torch.tensor([[0.1, 6.0, -2.0, 3.2]])

# Create a one-hot encoded vector of the label y
one_hot_label = F.one_hot(torch.tensor(y), num_classes=4)
one_hot_label

tensor([0, 0, 1, 0])

In [30]:
import torch.nn.functional as F

y = [2]
scores = torch.tensor([[0.1, 6.0, -2.0, 3.2]])

# Create a one-hot encoded vector of the label y
one_hot_label = F.one_hot(torch.tensor(y), scores.shape[1])

# Create the cross entropy loss function
criterion = nn.CrossEntropyLoss()

# Calculate the cross entropy loss
loss = criterion(scores.double(),one_hot_label.double())
print(loss)

tensor(8.0619, dtype=torch.float64)


our goal is to minimise the loss. Higher the loss, bad the model is. So derivaties are used to minimize the loss the loss function
## Using derivatives to update model parameters

we calculate the Gradient of loss function and use that to train the model using backpropogation. so that weight and bias are assgined properly.

loss function used in deep learning is non-convex. 
to find the global minimum of non-convex, we use mechnism called 'Gradient descent'

In PyTorch,an Optimizer takes care of Weight updates. 

Most common Optimizer is SGD (stochastic gradient descent) 



In [ ]:
import torch.optim as optim
# Create the optimizer
optimizer = optim.SGD(model.parameters), lr=0.001)

## Optimizer handles updating model parameters (or weights) after calculation of local gradients

optimizer.step()

In [ ]:
## Practice

criterion = nn.CrossEntropyLoss()

# Calculate the loss
loss = criterion(preds, target)

# Compute the gradients of the loss
loss.backward()

# Display gradients of the weight and bias tensors in order
print(weight.grad)
print(bias.grad)

In [ ]:
model = nn.Sequential(nn.Linear(16, 8),
                      nn.Sigmoid(),
                      nn.Linear(8, 2))

# Access the weight of the first linear layer
weight_0 = model[0].weight

# Access the bias of the second linear layer
bias_1 = model[2].bias

##Without PyTorch

weight0 = model[0].weight
weight1 = model[1].weight
weight2 = model[2].weight

# Access the gradients of the weight of each linear layer
grads0 = weight0.grad
grads1 = weight1.grad
grads2 = weight2.grad

# Update the weights using the learning rate and the gradients
weight0 = weight0 - lr*grads0
weight1 = weight1 - lr*grads1
weight2 = weight2 - lr*grads2


#This is too Tedious


In [ ]:
import torch.optim as optim # Create the optimizer
optimizer = optim.SGD(model.parameters(),lr=0.001)

loss = criterion(pred, target)
loss.backward()

# Update the model's parameters using the optimizer
optimizer.step()

##SGD is only one of the many optimizers implemented in PyTorch. 
##Researchers keep on improving the optimization process for training.

##CrossEntropyLoss function is only used for classification problem. 

## criterion = nn.MSEloss()
# loss = criterion(prediction, target) where prediction and target must be float tensors.

## Writing our first training loop

In [31]:
import numpy as np
y_hat = np.array(10)
y = np.array(1)

# Calculate the MSELoss using NumPy
mse_numpy = np.mean((y_hat - y) ** 2)

# Create the MSELoss function
criterion = torch.nn.MSELoss()

# Calculate the MSELoss using the created loss function
mse_pytorch = criterion(torch.tensor(y_hat).float(), torch.tensor(y).float())
print(mse_pytorch)

tensor(81.)


In [32]:
# we will write a training loop every time we train a deep learning model with PyTorch.
# Loop over the number of epochs and the dataloader
for i in range(num_epochs):
  for data in dataloader:
    # Set the gradients to zero
    optimizer.zero_grad()
    # Run a forward pass
    feature, target = data
    prediction = model(feature)    
    # Calculate the loss
    loss = criterion(prediction, target)    
    # Compute the gradients
    loss.backward()
    # Update the model's parameters
    optimizer.step()
show_results(model, dataloader)
    

NameError: name 'num_epochs' is not defined

## Discovering activation functions between layers
Sigmoid and SoftMax functions are used at last layer. Sigmoid and Softmax functions are varies between 0 and 1 and it create lot's limitation in training the network challenging. it's also called Vanishing Gradient. 

## Introducing ReLU

F(x) = Max(x,0)

In [ ]:
relu = nn.ReLU()
leaky_relu = nn.LeakyReLU(negative_slope = 0.05)

In [ ]:
# Create a ReLU function with PyTorch
relu_pytorch = nn.ReLU()

# Apply your ReLU function on x, and calculate gradients
x = torch.tensor(-1.0, requires_grad=True)
y = relu_pytorch(x)
y.backward()

# Print the gradient of the ReLU function for x
gradient = x.grad
print(gradient)

##Notice that the input value was zero, and the ReLU function turns any negative input to zero. 
##Recall from the graph in the video that for negative values of x, the output of ReLU is always zero, 
## and indeed the gradient is zero everywhere 
## because there is no change in the function with respect to any negative value of x.